[workspace]
preview = ["pixi-build"]
authors = ["Mehmet Keçeci <enfo@tuta.io>"]
channels = ["pypi", "https://prefix.dev/conda-forge", "https://conda.modular.com/max-nightly", "conda-forge", "https://repo.prefix.dev/modular-community"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
name = "oresmen"
version = "0.2.3"

[package]
name = "oresmen"
version = "0.2.3"
license = "AGPL-3.0-or-later"

[dependencies]
python = ">=3.11"
pip = ">=25.3"
numba = ">=0.65.1"
conda-build = ">=25.11.1"
setuptools = ">=82.0.1"
wheel = ">=0.45.1"
setuptools_scm = ">=9.2.2"
rattler-build = ">=0.55.0"
pytest = "*"
hatchling = ">=1.29.0"
poetry = ">=2.5.0"

[tasks]
build = "python -m build"
start = "python -c 'import oresmen; print(oresmen.__version__)'"
lint = "ruff check ."
fmt = "ruff format ."
serve = { cmd = "python -m http.server", cwd = "docs" }
install-oresmen = "pip install git+https://github.com/WhiteSymmetry/oresmen"
install = "pip install -e ."
test = { depends-on = ["install"], cmd = "pytest" }

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package.host-dependencies]
python = ">=3.11"
setuptools = ">=84.0.0"
cython = ">=3.0"
pip = "*"
